name: CDK Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # Required for OIDC to work
  contents: read        # To access the code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Lambda dependencies into function folder
        run: |
          pip install -r lambda/provision/requirements.txt -t lambda/provision/

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCDeployRole
          aws-region: eu-central-1

      - name: CDK Synth & Deploy
        run: |
          cdk synth
          cdk deploy --require-approval never